# The recommended basic settings for GNN
out_dir: results
device: auto
dataset:
  format: PyG
  load_type: pointwise
  name: beeradvocate
  task: link_pred
  task_type: ranking
  transductive: True
  split: [0.8, 0.1, 0.1]
  node_encoder: True
  node_encoder_name: one-hot
  edge_negative_sampling_ratio: 0.0
  encoder_dim: 64
train:
  batch_size: 4096
  eval_period: 1
  ckpt_period: 20
  ckpt_clean: False
  negative_sample_k: 1
  negative_sample_method: uniform
model:
  type: mcgnn
  loss_type: ranking
  eval_type: ranking
  loss_fun: bpr
  edge_decoding: dot
gnn:
  component_num: 1
  component_aggr: mean
  layers_pre_mp: 0
  layers_mp: 1
  layers_post_mp: 2
  dim_inner: 64
  layer_type: none
  stage_type: stack
  act: identity
  dropout: 0.0
  msg: identity
  batchnorm: True
  l2norm: False
optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 50
  weight_decay: 0.01
  scheduler: none
topk: 20
metric_best: recall
skip_existing_exp: False
