dataset:
  edge_negative_sampling_ratio: 0.0
  encoder_dim: 64
  format: PyG
  load_type: pointwise
  name: amazon-sports
  node_encoder: true
  node_encoder_name: one-hot
  split:
  - 0.8
  - 0.1
  - 0.1
  standardization: true
  task: link_pred
  task_type: regression
  transductive: true
device: auto
gnn:
  act: sigmoid
  batchnorm: true
  component_aggr: att
  component_num: 4
  dim_inner: 64
  dropout: 0.0
  l2norm: true
  layer_type: sageconv
  layers_mp: 1
  layers_post_mp: 1
  layers_pre_mp: 0
  msg: identity
  stage_type: mean
metric_best: rmse
model:
  edge_decoding: summation
  eval_type: non-ranking
  loss_fun: mse
  size_average: mean
  type: mcgnn
optim:
  base_lr: 0.01
  max_epoch: 200
  optimizer: adam
  weight_decay: 5e-3
out_dir: results/RGCF
skip_existing_exp: false
topk: 20
train:
  batch_size: 4096
  ckpt_clean: false
  ckpt_period: 1000
  eval_period: 20
