bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
dataset:
  augment_feature: []
  augment_feature_dims: []
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  cache_load: false
  cache_save: false
  custom_split: false
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: true
  edge_encoder_name: Bond
  edge_message_ratio: 0.81
  edge_negative_sampling_ratio: 0.0
  edge_train_mode: all
  encoder_dim: 64
  format: PyG
  load_type: pointwise
  name: beeradvocate
  node_encoder: true
  node_encoder_bn: true
  node_encoder_name: one-hot
  remove_feature: false
  split:
  - 0.8
  - 0.1
  - 0.1
  task: link_pred
  task_type: regression
  transductive: true
  transform: none
  tu_simple: true
device: auto
example_arg: example
example_group:
  example_arg: example
gnn:
  act: relu
  add_self_loop: true
  agg: add
  att: false
  att_final_linear: false
  att_final_linear_bn: false
  att_heads: 1
  batchnorm: true
  combine: add
  component_aggr: att
  component_num: 1
  dim_inner: 64
  dropout: 0.0
  keep_edge: 0.5
  l2norm: true
  layer_type: none
  layers_mp: 1
  layers_post_mp: 1
  layers_pre_mp: 0
  msg: hadamard
  msg_direction: single
  normalize_adj: false
  skip_every: 1
  stage_type: mean
mem:
  inplace: false
metric_best: rmse
model:
  edge_decoding: summation
  graph_pooling: add
  loss_fun: mse
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: mcgnn
num_threads: 6
num_workers: 0
optim:
  base_lr: 0.01
  lr_decay: 0.1
  max_epoch: 160
  momentum: 0.9
  optimizer: adam
  scheduler: cos
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.0005
out_dir: results/RGCF
print: both
round: 4
seed: 1
skip_existing_exp: false
tensorboard_agg: true
tensorboard_each_run: false
topk: 20
train:
  auto_resume: false
  batch_size: 4096
  ckpt_clean: false
  ckpt_period: 1000
  epoch_resume: -1
  eval_period: 2
  mode: standard
  node_per_graph: 32
  radius: extend
  sample_node: false
val:
  node_per_graph: 32
  radius: extend
  sample_node: false
view_emb: false
